# Generated by Django 6.0.6 on 2026-08-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='commission_fixed_on_policy_fee_lte_ass_policy_fee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='commission_configured_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='commission_configured_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='commission_fixed_on_policy_fee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='commission_percent_on_prime_rc',
        ),
    ]
