# Generated by Django 6.0.5 on 2026-06-02 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('AUTO_MONO', 'Auto mono'), ('MOTO', 'Moto'), ('FLEET', 'Flotte'), ('BUS_SCHOOL', 'Bus ecole'), ('GARAGE', 'Garage')], max_length=30)),
                ('internal_status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('QUOTE_READY', 'Devis pret'), ('PAYMENT_PENDING', 'Paiement en attente'), ('PAID', 'Paye'), ('ISSUED', 'Emis'), ('CANCELLED', 'Annule')], default='DRAFT', max_length=30)),
                ('ass_status', models.CharField(blank=True, choices=[('BROUILLON', 'Brouillon'), ('ANNULE', 'Annule'), ('VALIDE', 'Valide')], max_length=30, null=True)),
                ('reference_trx_partner', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('prime_rc_ass', models.PositiveIntegerField(blank=True, null=True)),
                ('cout_police_ass', models.PositiveIntegerField(default=3000)),
                ('ttc_ass', models.PositiveIntegerField(blank=True, null=True)),
                ('immatriculation', models.CharField(blank=True, max_length=50)),
                ('attestation_number', models.CharField(blank=True, max_length=120)),
                ('secure_key', models.CharField(blank=True, max_length=255)),
                ('reference_externe', models.CharField(blank=True, max_length=120)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('link_attestation_digitale', models.URLField(blank=True, max_length=500)),
                ('link_attestation_cedeao', models.URLField(blank=True, max_length=500)),
                ('ass_request_payload', models.JSONField(blank=True, default=dict)),
                ('ass_response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
