# Generated by Django 6.0.5 on 2026-06-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='draft_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
