# Generated by Django 6.0.5 on 2026-06-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_draft_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='ass_issue_request_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contract',
            name='ass_issue_response_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
