# Generated by Django 6.0.6 on 2026-06-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_ass_issue_request_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='issuance_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='internal_status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('QUOTE_READY', 'Devis pret'), ('PAYMENT_PENDING', 'Paiement en attente'), ('PAID', 'Paye'), ('ISSUING', 'Emission en cours'), ('ISSUED', 'Emis'), ('CANCELLED', 'Annule')], default='DRAFT', max_length=30),
        ),
    ]
