# Generated by Django 6.0.6 on 2026-06-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contract_search_text_trigram_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='policyholder_email',
            field=models.CharField(blank=True, editable=False, max_length=254),
        ),
        migrations.AddField(
            model_name='contract',
            name='policyholder_first_name',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='contract',
            name='policyholder_last_name',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='contract',
            name='policyholder_person_type',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='contract',
            name='policyholder_phone',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20),
        ),
    ]
