# Generated by Django 6.0.5 on 2026-06-02 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PAYABLE', 'Payable'), ('PAID', 'Payee'), ('CANCELLED', 'Annulee'), ('DISPUTED', 'Contestee')], default='PENDING', max_length=20)),
                ('prime_rc_ass', models.PositiveIntegerField()),
                ('cout_police_ass', models.PositiveIntegerField()),
                ('ttc_ass', models.PositiveIntegerField()),
                ('commission_percent_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_fixed_policy_fee_used', models.PositiveIntegerField()),
                ('commission_prime_rc_amount', models.PositiveIntegerField()),
                ('commission_policy_fee_amount', models.PositiveIntegerField()),
                ('commission_total', models.PositiveIntegerField()),
                ('net_to_horus', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission_snapshot', to='contracts.contract')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
