# Generated by Django 6.0.6 on 2026-06-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_commissionsnapshot_paid_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionsnapshot',
            name='net_to_horus',
        ),
        migrations.AddField(
            model_name='commissionsnapshot',
            name='ass_partner_commission',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commissionsnapshot',
            name='marge_horus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commissionsnapshot',
            name='montant_reverse_ass',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
