# Generated by Django 6.0.6 on 2026-08-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_remove_commissionsnapshot_net_to_horus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionsnapshot',
            name='ass_partner_commission_rate_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
