# Generated by Django 6.0.8 on 2026-09-09 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_commissionsnapshot_ass_partner_commission_rate_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionsnapshot',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Date du reversement a ASS.', null=True),
        ),
        migrations.AlterField(
            model_name='commissionsnapshot',
            name='paid_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant marque le solde comme reverse a ASS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_commission_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commissionsnapshot',
            name='status',
            field=models.CharField(choices=[('PENDING', 'A reverser'), ('PAYABLE', 'Pret a reverser'), ('PAID', 'Reverse a ASS'), ('CANCELLED', 'Annulee'), ('DISPUTED', 'Contestee')], default='PENDING', max_length=20),
        ),
    ]
