# Generated by Django 6.0.8 on 2026-09-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_alter_commissionsnapshot_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionsnapshot',
            name='remise_horus',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
