# Generated by Django 6.0.6 on 2026-06-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=120)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'journal appel ASS',
                'verbose_name_plural': 'journal appels ASS',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endpoint', 'created_at'], name='ass_assapil_endpoin_7fdf1a_idx')],
            },
        ),
    ]
