# Generated by Django 6.0.6 on 2026-07-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_unique_confirmed_payment_per_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('MANUAL', 'Manuel'), ('ORANGE_MONEY', 'Orange Money')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='om_transaction_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
