# Generated by Django 6.0.8 on 2026-09-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_method_payment_om_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='om_qr_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
